apiVersion: v1
kind: Pod
metadata:
  name: test-jwt-pod
  namespace: default
spec:
  containers:
  - name: sleeper
    image: debian:bookworm-slim
    command: ["sleep", "infinity"]
  serviceAccountName: default
